(function(){function f(){var cm="/products-ai-agents-care-management",cg="/products-ai-agents-care-gaps",rc="/resources-case-studies",za="/zynix-ai-agents",zah="/products-ai-agents-zynafterhours";var M={"/case-studies/amistad":rc,"/case-studies/apollo-clinic":rc,"/case-studies/nhs":rc,"/case-studies/pbaco":rc,"/chronic-care-management":cm,"/transitions-of-care":cm,"/preventive-quality-activation":cg,"/sdoh-determination":cm,"/agents":za,"/operational-efficiency/zynafterhours-triage":zah,"/use-cases/after-hours-ed-diversion-aco":"/use-cases/after-hours-ed-diversion","/platform":"/platform-legacy","/blog":"/resources-blog","/faq":"/resources-faq","/case-studies":rc};var I="acos-msos ascs health-plans health-systems fqhcs independent-group-practices zynix-data-analytics zynix-ai-agents".split(" "),D={"acos":"/acos-msos","independent-practices":"/independent-group-practices","zyngap":cg,"zynafterhours":zah,"zynschedule":"/products-ai-agents-zynschedule","zynauth":"/products-ai-agents-zynauth","zynfax":"/products-ai-agents-zynfax","zynreminder":"/products-ai-agents-zynreminder","clinical-performance":za,"clinical-performance-agents":za};I.forEach(function(s){D[s]="/"+s});var PR=[[/^\/who-we-serve\//,"/"],[/^\/company\//,"/company-"],[/^\/products\//,"/products-"],[/^\/resources\/blog\//,"/blog-"],[/^\/resources-blog\//,"/blog-"],[/^\/resources\//,"/resources-"],[/^\/blog\//,"/blog-"],[/^\/case-studies\//,"/case-studies-"]];var PF=[[/^\/agents\//,za],[/^\/operational-efficiency\//,za],[/^\/chronic-care-management\//,cm],[/^\/preventive-quality-activation\//,cg]];
// External URL fixes — 404 destinations rewritten to working equivalents
var EXT={
"https://www.cms.gov/medicare/shared-savings-program/about":"https://www.cms.gov/priorities/innovation/innovation-models/aco",
"https://www.cms.gov/medicare/physician-fee-schedule/transitional-care-management-services":"https://qpp.cms.gov/mips/quality-measures",
"https://www.mgma.com/data/benchmarking-data":"https://www.mgma.com/",
"https://www.ama-assn.org/practice-management/prior-authorization/prior-authorization-and-administrative-burden":"https://www.ama-assn.org/topics/prior-authorization",
"https://www.cms.gov/medicare/health-plans/medicareadvtgspecratestats/star-ratings":"https://www.medicare.gov/care-compare"
};
var a=document.querySelectorAll("a[href]");for(var i=0;i<a.length;i++){var h=a[i].getAttribute("href");if(!h)continue;
// External rewrite check
if(EXT[h]){a[i].setAttribute("href",EXT[h]);continue}
if(h.charAt(0)!=="/")continue;var p=h.split("#")[0].split("?")[0];var r=h.substring(p.length);if(M[p]){a[i].setAttribute("href",M[p]+r);continue}var sm=p.match(/^\/solutions[\/-](.+)$/);if(sm){if(D[sm[1]])a[i].setAttribute("href",D[sm[1]]+r);continue}var d=0;for(var j=0;j<PR.length;j++){if(PR[j][0].test(p)){a[i].setAttribute("href",p.replace(PR[j][0],PR[j][1])+r);d=1;break}}if(d)continue;for(var k=0;k<PF.length;k++){if(PF[k][0].test(p)){a[i].setAttribute("href",PF[k][1]+r);break}}}}if(document.readyState==="loading"){document.addEventListener("DOMContentLoaded",f)}else{f()}setTimeout(f,1500);})();
